### ISSUE TITLE
Error when calling Color from C/C++

### ISSUE THREAD

**Issue by FrezZyyyx** [ExtReMLapin/BadCoderz#10]
[ERROR] addons/[gmodstore]_badcoderz/lua/badcoderz/sh_luajit_decompiler.lua:21: bad argument #1 to 'funcuvname' (function expected, got function)
  1. funcuvname - [C]:-1
   2. disassemble_function - addons/[gmodstore]_badcoderz/lua/badcoderz/sh_luajit_decompiler.lua:21
    3. find_color_call_static_args - addons/[gmodstore]_badcoderz/lua/badcoderz/sh_luajit_decompiler.lua:81
     4. unknown - addons/[gmodstore]_badcoderz/lua/badcoderz/sh_work.lua:68
      5. unknown - lua/includes/util/color.lua:14
       6. unknown - [C]:-1

what does this mean

**Comment by ExtReMLapin** [comment]
It means a C function is calling Color for some reasons and It should not happen.

**Comment by ExtReMLapin** [comment]
I'm already working on another update so this fix will have to wait.

**Comment by ExtReMLapin** [comment]
Fixed in 42c035433af05fb3c7fd75d4c54b9c7563fd3844
