### ISSUE TITLE
Color on PANEL:Paint being a issue

### ISSUE THREAD

**Issue by stevensky45** [ExtReMLapin/BadCoderz#15]
```lua
local PANEL = {}

function PANEL:Init()
	self:Dock(FILL)
end

function PANEL:Paint(w, h)
	draw.RoundedBox(0, 0, 0, w, h, Color(255, 0, 0))
end

vgui.Register('home_panel', PANEL, 'Panel')
```

it seems that this isn't a optimal use of draw.RoundedBox, instead it would be better to use a variable, so:

```lua
local PANEL = {}

function PANEL:Init()
	self:Dock(FILL)
	self.color1 = Color(255, 0, 0)
end

function PANEL:Paint(w, h)
	draw.RoundedBox(0, 0, 0, w, h, self.color1)
end

vgui.Register('home_panel', PANEL, 'Panel')
```

so my conclusion on this is that BadCoderz is showing that you shouldn't use the Color function on PANEL:Paint, because it would be runned multiple times, so instead one should use a variable so the Color function only runs once, am I correct?

also, it's weird because we usually learn the first method, and [the wiki](https://wiki.facepunch.com/gmod/PANEL:Paint) shows a example like that

**Comment by ExtReMLapin** [comment]
Yes the issue here is `Color` being called everytime, just cache the color outside , you don't even need to store it inside the panel instance.

To be honest, Recreating color object on each frame isn't going to destroy performances but it's still a code smell.

Also when you put your mouse over the function name it gives you intel about what to do and what's the issue about the hook/function.

**Comment by ExtReMLapin** [comment]
I wouldn't follow the wiki for everything they show/give.

Here is an example : https://wiki.facepunch.com/gmod/ents.FindByClass

On this page, **on the old wiki**, they said using ents.FindByClass isn't faster than using ents.GetAll as they claim GetAll is used internally by FindByClass.
It's obviously wrong as the work done on C++ side is faster than the work done on Lua/LuaJIT side. I had to change this on the wiki.

Gmod's code itself can be  terrible sometimes.
For example garry created this function : https://wiki.facepunch.com/gmod/table.HasValue

Literally NO ONE gave a fuck for literally 10 years.
Then I add it to badcoders and people adds warning on it on the wiki.

**Comment by ExtReMLapin** [comment]
There are really few really good developers on GMod, and having this kind of shitty functions available to use leads to shitty code https://github.com/ExtReMLapin/gHomes/search?q=hasvalue

**Comment by stevensky45** [comment]
I see, thank you for the response, and I usually use the good example on [Tables: Bad Habits](https://wiki.facepunch.com/gmod/Tables:_Bad_Habits) to check if a table has a value, like:
```lua
local AllowedVehicles = {
	prop_vehicle_jeep = true,
```
so:
```lua
if AllowedVehicles[veh:GetClass()] then
```
and btw, why you didn't used the above method on gHomes?

also, I find it funny that you refer to it as 'code smell' haha

edit: I'm getting this on console "Var type table is not implemented in BadCoderz, pls tell the dev" when starting BadCoderz and selecting some stools like weld, button and light

**Comment by ExtReMLapin** [comment]
I didn't use it in ghomes because i didn't know about hashtables at this time, for real.

About the table warning it's happen on metatable calls, im just too lazy to implement it

**Comment by stevensky45** [comment]
nvm
